# -*- coding: utf-8 -*-

# GNU General Public License v3.0 (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, unicode_literals

# https://services.vrt.be/htmlview/?href=%2Fchannel%2Fs&rel=http%3A%2F%2Fservices.vrt.be%2Fchannel%2Frel%2Fchannels
CHANNELS = [

    dict(
        id='10',
        name='R1',
        label='NPO Radio 1',
        tagline='Wie luistert NPO RADIO 1 weet meer',
        website='https://www.nporadio1.nl',
        mpeg_dash_128='npodash',
        mp3_128='https://icecast.omroep.nl/radio1-bb-mp3',
        aac_128='https://icecast.omroep.nl/radio1-bb-aac',
        logo='https://raw.githubusercontent.com/3DSBricker/plugin.audio.nl.radio/master/images/npo_radio1_logo.png',
        backdrop='npobackupimage',
        epg_id='radio1.nl',
        preset=1,
    ),
    dict(
        id='20',
        name='R2',
        label='NPO Radio 2',
        tagline='Er is maar één NPO Radio 2',
        website='https://www.nporadio2.nl',
        mpeg_dash_128='npodash',
        mp3_128='https://icecast.omroep.nl/radio2-bb-mp3',
        aac_128='https://icecast.omroep.nl/radio2-bb-aac',
        logo='https://raw.githubusercontent.com/3DSBricker/plugin.audio.nl.radio/master/images/npo_radio2_logo.png',
        backdrop='npobackupimage',
        epg_id='radio2.nl',
        preset=2,
    ),
    dict(
        id='21',
        name='R2_SJ',
        label='NPO Radio 2 Soul & Jazz',
        tagline='Dé radiozender voor soul, jazz en alles daar tussen!',
        website='https://www.nporadio2.nl/soulenjazz',
        mpeg_dash_128='npodash',
        mp3_128='https://icecast.omroep.nl/radio6-bb-mp3',
        aac_128='https://icecast.omroep.nl/radio6-bb-aac',
        logo='https://raw.githubusercontent.com/3DSBricker/plugin.audio.nl.radio/master/images/npo_radio2_soul_en_jazz_logo.png',
        backdrop='npobackupimage',
        epg_id='radio2sj.nl',
        preset=3,
    ),
    dict(
        id='22',
        name='SNL',
        label='NPO SterrenNL',
        tagline='De nummer 1 in Nederlandstalige muziek',
        website='https://www.nporadio5.nl/sterrennl',
        mpeg_dash_128='npodash',
        mp3_128='https://icecast.omroep.nl/radio2-sterrennl-mp3',
        aac_128='https://icecast.omroep.nl/radio2-sterrennl-aac',
        logo='https://raw.githubusercontent.com/3DSBricker/plugin.audio.nl.radio/master/images/npo_sterrennl_logo.png',
        backdrop='npobackupimage',
        epg_id='sterren.nl',
        preset=4,
    ),
    dict(
        id='30',
        name='3FM',
        label='NPO 3FM',
        tagline='We Want More',
        website='https://www.npo3fm.nl',
        mpeg_dash_128='npodash',
        mp3_128='https://icecast.omroep.nl/3fm-bb-mp3',
        aac_128='https://icecast.omroep.nl/3fm-bb-aac',
        logo='https://raw.githubusercontent.com/3DSBricker/plugin.audio.nl.radio/master/images/3fm-logo.png',
        backdrop='npobackupimage',
        epg_id='3fm.nl',
        preset=5,
    ),
    dict(
        id='31',
        name='3FM_ALT',
        label='NPO 3FM Alternative',
        tagline='Music Starts Here',
        website='https://www.npo3fm.nl/alternative',
        mpeg_dash_128='npodash',
        mp3_128='https://icecast.omroep.nl/3fm-alternative-mp3',
        aac_128='https://icecast.omroep.nl/3fm-alternative-aac',
        logo='https://www.npo3fm.nl/alternative/images/alternative-logo.webp',
        backdrop='npobackupimage',
        epg_id='3fmalt.nl',
        preset=6,
    ),
    dict(
        id='32',
        name='3FM_KX',
        label='NPO 3FM KX Radio',
        tagline='Talent Radio',
        website='https://www.npo3fm.nl/kx',
        mpeg_dash_128='npodash',
        mp3_128='https://icecast.omroep.nl/3fm-serioustalent-mp3',
        aac_128='https://icecast.omroep.nl/3fm-serioustalent-aac',
        logo='https://www.npo3fm.nl/kx/images/kx-logo.webp',
        backdrop='npobackupimage',
        epg_id='3fmkx.nl',
        preset=7,
    ),

]
